### ISSUE TITLE
Server: Implement Youtube API

### ISSUE THREAD

**Issue by khoaquocngo** [VC-Team/yemusic#17]
# Changes

- Implement get list song

### Get list song

- Route: `api/song/s`
- Method: `POST`

- Input:

    ```js
    {
      "search": string,
      "token": string
      "apikey": string
    }
    ```

    where:

    | Fields | Description                                      | Notes |
    |--------|--------------------------------------------------|-------|
    | search | search song                                      |       |
    | token  | Key to get more data (next/prev page result)     |       |
    | apikey | Api key to get more data (next/prev page result) |       |

- Responses:

    ```js
    {
      isSuccess: Boolean
      token: String,
      apikey: String,
      songs: [{
        "youtubeId": String,
        "title": String,
        "thumbnail": {
          url: String,
          width: Number,
          height: Number
        },
        "duration": String,
        "publishedAt": Date
        "channel": String,
        "view": String,
      }]
    }
    ```

  where:

    | Fields    | Description                                      | Notes |
    |-----------|--------------------------------------------------|-------|
    | isSuccess | is the query executed successfully?              |       |
    | songs     | The list of songs                                |       |
    | token     | Key to get more data (next/prev page result)     |       |
    | apikey    | Api key to get more data (next/prev page result) |       |

  - songs

    where:

      | Fields      | Description                                                                                             | Notes |
      |-------------|---------------------------------------------------------------------------------------------------------|-------|
      | youtubeId   | Youtube identity                                                                                        |       |
      | title       | Title of song                                                                                           |       |
      | thumbnail   | - url: URL of song youtube thumbnail</br>- width: width of thumbnail</br>- height: height of  thumbnail |       |
      | duration    | Duration of                                                                                             |       |
      | publishedAt | Song published at                                                                                       |       |
      | channel     | Youtube channel                                                                                         |       |
      | view        | View of song                                                                                            |       |

### Get Audio Url

- Route: `api/song/:youtubeId`
- Method: `GET`
- Responses:

    ```js
    {
      isSuccess: Boolean
      message: String
      audioUrl: String,
    }
    ```

   where:

    | Fields    | Description                         | Notes |
    |-----------|-------------------------------------|-------|
    | isSuccess | is the query executed successfully? |       |
    | message   | error message                       |       |
    | audioUrl  | Audio Url by youtubeId              |       |

## Refer

- [usetube](https://github.com/valerebron/usetube)

**Comment by gialynguyen** [comment]
This should have pagination. Right?

**Comment by gialynguyen** [comment]
The first time you search, the `searchVideo` will return the `token` field beside videos and you could use this token to load more later.

**Comment by khoaquocngo** [comment]
> The first time you search, the `searchVideo` will return the `token` field beside videos and you could use this token to load more later.

Yes! Good idea. I'll try again tomorrow
