### ISSUE TITLE
Server: API Sign Up

### ISSUE THREAD

**Issue by trungpham71198** [VC-Team/yemusic#21]

**Comment by tunganh252** [comment]
## Changes

- Update schema `User`
- Update sub-Schema `InfoUser`

## MongoDB

```js
const userSchema = new Schema(
  {
    email: { type: String, unique: true, required: true },
    username: { type: String, unique: true },
    password: { type: String, required: true },
    phone: { type: String, unique: true },
    desc: String,
    info: userInfo,
    token: String,
    refreshToken: String,
    refreshTokenExpires: Date,
    isValidEmail: {
      type: Boolean,
      default: false,
    },
    isBlocked: {
      type: Boolean,
      default: false,
    },
  },
  { timestamps: true }
);
```

where:

  | Fields       | Description              | Notes  |
  | ------------ | ------------------------ | ------ |
  | email        | Email address of User    | Unique, Required |
  | username     | Username                 | Unique |
  | password     | Password                 | Required  |
  | phone        | Phone number of User     | Unique |
  | desc        | description of User      |        |
  | info         | [UserInfo](#UserInfo)    |        |
  | token        | token for authentication      |        |
  | refreshToken        | refreshToken to get new token |        |
  | refreshTokenExpires | expired time of refreshToken |        |
  | isValidEmail | Mark user as valid email | Default = false     |
  | isBlocked    | Mark user as blocked     |  Default = false     |

### UserInfo

```js
const userInfo = new Schema(
  {
    firstName: String,
    lastName: String,
    displayName: String,
    avatarUrl: String,
    gender: {
      type: String,
      enum: ['Male', 'Female', 'Other'],
    },
  },
  { _id: false, id: false }
);
```

where:

  | Fields      | Description        | Notes               |
  | ----------- | ------------------ | ------------------- |
  | firstName   | First name         |            |
  | lastName    | Last name          |            |
  | displayName | Display name       |                     |
  | avatarUrl   | Avatar url of User |                     |
  | gender      | Gender of user     | Male, Female, Other |

**Comment by tunganh252** [comment]
# Sign-up API

- Route: `/api/auth/sign-up`
- Method: `POST`
- Input:

```js
{
  "email": string,
  "password": string
}
```

where:

  | Fields      | Description        | Notes               |
  | ----------- | ------------------ | ------------------- |
  | email   | email of user         | Unique            |
  | password      | password     |    |

- Responses:

```js
{
  isSuccess: Boolean,
  token: String,
  refreshToken: String
}

where:

  | Fields      | Description        | Notes               |
  | ----------- | ------------------ | ------------------- |
  | isSuccess   | is the query executed successfully?         |            |
  | token      | token for authentication     |    |
  | refreshToken      | get new token  |    |

**Comment by tunganh252** [comment]
# Send Email Verify API

- Route: `/api/auth/sendEmailVerify`
- Method: `POST`
- Input:

    ```js
    {
      "email": string
    }
    ```
    
    where:
    
  | Fields      | Description        | Notes               |
  | ----------- | ------------------ | ------------------- |
  | email   | email of user         |            |

- Responses: ***receive mail has link to verify account in personal mailbox***

  ```js
  {
    isSuccess: Boolean
  }
  ```
  
  where:
  
    | Fields      | Description        | Notes               |
    | ----------- | ------------------ | ------------------- |
    | isSuccess   | is the mutation executed successfully?  |            |

**Comment by tunganh252** [comment]
# Verify Email API

- Route: `/api/auth/verifyEmail/:tokenVerifyEmail`
- Method: `GET`
- Input:
- Responses:

  ```js
  {
    "isSuccess": Boolean,
    "data": userResponse
  }
  ```
  
  where:
  
  | Fields      | Description        | Notes               |
  | ----------- | ------------------ | ------------------- |
  | isSuccess   | is the mutation executed successfully?  |            |
  | data   | [userResponse](userResponse)  |            |

    ### userResponse
    
     ```js
     {
        "_id": String
        "email": String,
        "username": String,
        "isValidEmail": Boolean,
        "isBlocked": Boolean,
        "createdAt": Date,
        "updatedAt": Date,
        "refreshToken": String,
        "refreshTokenExpires": Date,
        "token": String
     }
     ```
     where:
  
  | Fields      | Description        | Notes               |
  | ----------- | ------------------ | ------------------- |
  | _id   | id of user  |            |
  | email   | email address  |            |
  | username   | username  |            |
  | isValidEmail   | Mark user as valid email  |            |
  | isBlocked   | Mark user as valid block  |            |
  | createdAt   | Date when user created  |            |
  | updatedAt   | Date when user updated |            |
  | token   | token use for authentication |            |
  | refreshToken   | refreshToken use to get new token  |            |
  | refreshTokenExpires   | Date expired of  refreshToken |            |
