### ISSUE TITLE
Server: Create Models User

### ISSUE THREAD

**Issue by trungpham71198** [VC-Team/yemusic#30]
- Tùng anh and Tuấn discuss and create together models for User

**Comment by tuanbui050198** [comment]
{
  userId: string,
  token: string,
  userName: string,
  email?: string,
  avatarUrl: string,
  userGender: male | female | other,
  createdAt: number | string;
  updatedAt?: number | string;
} @tunganh252  @khoaquocngo  @trungpham71198

**Comment by khoaquocngo** [comment]
> ```js
> const UserSchema = new Schema({
>   // ...others
>   info: InfoUser,
>   email: string,
>   phone?: string,
>   avatarUrl?: string,
>   gender?: male | female | other,
>   password:string,
> })
> 
> const InfoUser = new Schema({
>   // ...others
>   username: string,
>   firstName: string,
>   lastName: string,
>   displayName?: string,
> })
> @trungpham71198  @khoaquocngo  
> ```

https://mongoosejs.com/docs/guide.html#schemas

**Comment by tuanbui050198** [comment]
```js
const SomeSchema = new Schema({
  // ...others
  info: { type: ObjectId, ref: 'InfoUser' },
  email: String,
  phone?: String,
  avatarUrl?: String,
  gender?: ['male', 'female', 'other'],
  password:String,
})

const InfoUser = new Schema({
  // ...others
  username: String,
  firstName: String,
  lastName: String,
  displayName?: String,
})

**Comment by khoaquocngo** [comment]
## Changes

- Add schema `User`
- Add sub-Schema `InfoUser`

## MongoDB

```js
const UserSchema = new Schema({
  username: {
    type: String,
    unique: true,
  },
  password: String,

  descr: string,
  info: UserInfo
  
  email: {
    type: String,
    unique: true
  }
  phone: {
    type: String,
    unique: true
  }
  
  isValidEmail: Boolean,
  isBlocked: Boolean,
}, { timestamps: true })
```

where:

  | Fields       | Description              | Notes  |
  | ------------ | ------------------------ | ------ |
  | username     | Username                 | Unique |
  | password     | Password                 |        |
  | info         | [UserInfo](#UserInfo)    |        |
  | email        | Email address of User    | Unique |
  | phone        | Phone number of User     | Unique |
  | isValidEmail | Mark user as valid email |        |
  | isBlocked    | Mark user as blocked     |        |

### UserInfo

```js
const UserInfoSchema = new Schema({
  firstName: {
    type: String,
    required: true
  },
  lastName: {
    type: String,
    required: true
  },
  displayName: String,
  avatarUrl: String,
  gender: {
    type: String,
    enum: ['Male', 'Female', 'Other'] 
  },
}, { _id: false, id: false});
```

where:

  | Fields      | Description        | Notes               |
  | ----------- | ------------------ | ------------------- |
  | firstName   | First name         | Required            |
  | lastName    | Last name          | Required            |
  | displayName | Display name       |                     |
  | avatarUrl   | Avatar url of User |                     |
  | gender      | Gender of user     | Male, Female, Other |

**Comment by khoaquocngo** [comment]
> ## Changes
> * Add schema `User`
> * Add sub-Schema `InfoUser`
> 
> ## MongoDB
> ```js
> const UserSchema = new Schema({
>   username: {
>     type: String,
>     unique: true,
>   },
>   password: String,
> 
>   descr: string,
>   info: UserInfo
>   
>   email: {
>     type: String,
>     unique: true
>   }
>   phone: {
>     type: String,
>     unique: true
>   }
>   
>   isValidEmail: Boolean,
>   isBlocked: Boolean,
> }, { timestamps: true })
> ```
> 
> where:
> 
> Fields	Description	Notes
> username	Username	Unique
> password	Password	
> info	[UserInfo](#UserInfo)	
> email	Email address of User	Unique
> phone	Phone number of User	Unique
> isValidEmail	Mark user as valid email	
> isBlocked	Mark user as blocked	
> ### UserInfo
> ```js
> const UserInfoSchema = new Schema({
>   firstName: {
>     type: String,
>     required: true
>   },
>   lastName: {
>     type: String,
>     required: true
>   },
>   displayName: String,
>   avatarUrl: String,
>   gender: {
>     type: String,
>     enum: ['Male', 'Female', 'Other'] 
>   },
> }, { _id: false, id: false});
> ```
> 
> where:
> 
> Fields	Description	Notes
> firstName	First name	Required
> lastName	Last name	Required
> displayName	Display name	
> avatarUrl	Avatar url of User	
> gender	Gender of user	Male, Female, Other

@tunganh252 @tuanbui050198  `reference`
