### ISSUE TITLE
Server: Auditor

### ISSUE THREAD

**Issue by khoaquocngo** [VC-Team/yemusic#37]
I want to create a Audit Collection.

What does this component do?
- Step 1. Receive new audit request
- Step 2. Do some validations
- Step 3. Translate request into meaningful description
- Step 4. Save to database (Audit Schema)

How do you feel about that idea?

**Comment by gialynguyen** [comment]
What mean of "Audit" in this case?
Why is this issue called "Auditor" instead of "Audit"?
What are features that we can build by using this collection?

**Comment by khoaquocngo** [comment]
`What mean of "Audit" in this case?`
Audit is collection in this case

`Why is this issue called "Auditor" instead of "Audit"?`
I want to have a separate database named auditor  and collection audit. To facilitate management when the number of requests is too large.

`What are features that we can build by using this collection?`
In this project, the application is used. I think it will help with error checking in the application and control the number of access requests

**Comment by gialynguyen** [comment]
Why do we need a collection here? Why don't we implement API Rate Limiting? What are the differences?
