### ISSUE TITLE
Server: Setup Unit Test 

### ISSUE THREAD

**Issue by trungpham71198** [VC-Team/yemusic#58]

**Comment by gialynguyen** [comment]
@khoaquocngo @trungpham71198 any updates?

**Comment by khoaquocngo** [comment]
> @khoaquocngo @trungpham71198 any updates?

@trungpham71198 Setuping

**Comment by trungpham71198** [comment]
- Supertest: https://github.com/visionmedia/supertest
- Jest: https://jestjs.io/docs/api
