### ISSUE TITLE
Server: Update config for tsconfig.app.json 

### ISSUE THREAD

**Issue by trungpham71198** [VC-Team/yemusic#61]

**Comment by gialynguyen** [comment]
@trungpham71198 Update what? You must describe it in detail.

**Comment by gialynguyen** [comment]
@trungpham71198 update the description

**Comment by trungpham71198** [comment]
@gialynguyen  Due to some mistake when I ran the test, I thought the project was configured incorrectly, but it is not because I was wrong, so I will close this issue
